// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9octglmSGuKuE45DRrHpnvUT54makQ20',
    appId: '1:744338036100:web:d2091e7df2455d3139b9d1',
    messagingSenderId: '744338036100',
    projectId: 'tugaspertemuan9-31ae1',
    authDomain: 'tugaspertemuan9-31ae1.firebaseapp.com',
    storageBucket: 'tugaspertemuan9-31ae1.firebasestorage.app',
    measurementId: 'G-TX3L3LMYN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5m4jyL8yw1mxfZTdaNqi14VRwoVFiXE',
    appId: '1:744338036100:android:8893b2bff0fd09c939b9d1',
    messagingSenderId: '744338036100',
    projectId: 'tugaspertemuan9-31ae1',
    storageBucket: 'tugaspertemuan9-31ae1.firebasestorage.app',
  );
}
